export const ACCOUNT_IS_LOGGING_IN = 'ACCOUNT_IS_LOGGING_IN';
export const ACCOUNT_LOGIN_CANCELLED = 'ACCOUNT_LOGIN_CANCELLED';
export const ACCOUNT_LOGIN_ERROR = 'ACCOUNT_LOGIN_ERROR';
export const ACCOUNT_LOGIN_AUTHENTICATED = 'ACCOUNT_LOGIN_AUTHENTICATED';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
