export const ACCOUNT_IS_LOGGING_IN = 'ACCOUNT_IS_LOGGING_IN';
export const ACCOUNT_LOGIN_CANCELLED = 'ACCOUNT_LOGIN_CANCELLED';
export const ACCOUNT_LOGIN_ERROR = 'ACCOUNT_LOGIN_ERROR';
export const ACCOUNT_LOGIN_AUTHENTICATED = 'ACCOUNT_LOGIN_AUTHENTICATED';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const PLACES_LOAD_REQUESTED = 'PLACES_LOAD_REQUESTED';
export const PLACES_LOAD_ERROR = 'PLACES_LOAD_ERROR';
export const PLACES_LOAD_COMPLETED = 'PLACES_LOAD_COMPLETED';

export const EVENTS_LOAD_REQUESTED = 'EVENTS_LOAD_REQUESTED';
export const EVENTS_LOAD_ERROR = 'EVENTS_LOAD_ERROR';
export const EVENTS_LOAD_COMPLETED = 'EVENTS_LOAD_COMPLETED';
